version: '3'
networks:
  backend_db_net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - backend_db_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - backend_db_net
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend_db_net
    environment:
      - NEXT_PUBLIC_BACKEND_URL=/api

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: booklibrary
    networks:
      - backend_db_net
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost -u root -ppassword -e 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5